version: 2
jobs:
  build:
    working_directory: ~/to-do-list
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'yarn global add npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
          background: true

      - run:
          name: Run the application
          command: yarn start
          background: true

      - run: yarn run selenium-setup
      - run: yarn run selenium-setup
      - run: yarn run e2e-tests

      # - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "cf:7b:81:1d:0a:00:fd:c4:ab:ab:c5:cc:57:c0:89:0f"

      - checkout
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/setup-heroku.sh
              heroku version
              heroku update
              heroku container:push web
              heroku restart
            fi
